# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfd < Formula
  desc "Easy certificate management for development environments"
  homepage "https://www.certsfor.dev/"
  version "0.2.2"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.2/cfd_0.2.2_Darwin_x86_64.tar.gz"
    sha256 "e789996fb0599a42a2fe22b29e13466241360f1415ee6dc99cd156ea8b67fa26"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.2/cfd_0.2.2_Linux_x86_64.tar.gz"
    sha256 "2dd0731cabe8d7f589ac97012d21dd157d9cfd1753cf87f5b3756bb2a611a744"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.2/cfd_0.2.2_Linux_armv6.tar.gz"
    sha256 "762de3078feceac43cc2538702e7f3661da7cd39998f41f1e582150dcff0addb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.2/cfd_0.2.2_Linux_arm64.tar.gz"
    sha256 "0877297606f3c2a3406c34f3282c2f4d7e56ee6ff42168db3f0fb01351e5dd10"
  end

  def install
    bin.install "cfd"
  end

  test do
    system "#{bin}/cfd -h"
  end
end
