# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfd < Formula
  desc "Easy certificate management for development environments"
  homepage "https://www.certsfor.dev/"
  version "0.2.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.3/cfd_0.2.3_Darwin_x86_64.tar.gz"
    sha256 "8c6c5e34f54a105dc38c762b8bb4bd2b0f2439b0356413ae6b1cffc0fd863ade"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.3/cfd_0.2.3_Linux_x86_64.tar.gz"
    sha256 "f773f3bc11217a03f2e309acccce7191b72cde3c824c455a99e43e7c11e0d1c9"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.3/cfd_0.2.3_Linux_armv6.tar.gz"
    sha256 "a15f982ac2cf1f14115363f6bd6c5d61991aac27f4d892b051e3ad766174b3cd"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/fernandezvara/certsfor/releases/download/v0.2.3/cfd_0.2.3_Linux_arm64.tar.gz"
    sha256 "1bd028997aeaa1842a94252325ba569966c42fa26784ad07662a825b1d17bb04"
  end

  def install
    bin.install "cfd"
  end

  test do
    system "#{bin}/cfd -h"
  end
end
